### ISSUE TITLE
Got error after install requirements

### ISSUE THREAD

**Issue by bacquang98** [Krutyi-4el/DandelionMusic#14]
When install requirements, i got this erro

> ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

I changed aiohttp version to 3.8.2 then install complete. But when run run.py, i got this error

> D:\_Working\BackEnd\DandelionMusic-master>run.py
Traceback (most recent call last):
  File "D:\_Working\BackEnd\DandelionMusic-master\run.py", line 4, in <module>
    from discord.ext import commands
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\__init__.py", line 18, in <module>
    from .flags import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\flags.py", line 71, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

Im newbie to Python so i dont know how to fix it though im google this morning :(

**Comment by Krutyi-4el** [comment]
Try downgrading Python to 3.10

**Comment by Krutyi-4el** [comment]
#22 should've fixed this. Download the new version if you're facing the same issue.
