### ISSUE TITLE
Cannot play music

### ISSUE THREAD

**Issue by lokey0905** [Krutyi-4el/DandelionMusic#2]
[youtube] 9fMi070Fulw: Downloading webpage
[youtube] 9fMi070Fulw: Downloading android player API JSON
Playing https://www.youtube.com/watch?v=9fMi070Fulw
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\discord\ext\commands\core.py", line 184, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\lokey\OneDrive\桌面\DandelionMusic-master\musicbot\commands\music.py", line 43, in _play_song
    song = await audiocontroller.process_song(track)
  File "C:\Users\lokey\OneDrive\桌面\DandelionMusic-master\musicbot\audiocontroller.py", line 206, in process_song
    await self.play_song(song)
  File "C:\Users\lokey\OneDrive\桌面\DandelionMusic-master\musicbot\audiocontroller.py", line 143, in play_song
    discord.FFmpegPCMAudio(
  File "C:\python\lib\site-packages\discord\player.py", line 314, in __init__
    super().__init__(source, executable=executable, args=args, **subprocess_kwargs)
  File "C:\python\lib\site-packages\discord\player.py", line 174, in __init__
    self._process: subprocess.Popen = self._spawn_process(args, **kwargs)
  File "C:\python\lib\site-packages\discord\player.py", line 191, in _spawn_process
    raise ClientException(f"{executable} was not found.") from None
discord.errors.ClientException: ffmpeg was not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\python\lib\site-packages\discord\ext\commands\bot.py", line 344, in invoke
    await ctx.command.invoke(ctx)
  File "C:\python\lib\site-packages\discord\ext\commands\core.py", line 951, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\python\lib\site-packages\discord\ext\commands\core.py", line 193, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientException: ffmpeg was not found.
Exception ignored in: <function AudioSource.__del__ at 0x00000236DFC134C0>
Traceback (most recent call last):
  File "C:\python\lib\site-packages\discord\player.py", line 127, in __del__
    self.cleanup()
  File "C:\python\lib\site-packages\discord\player.py", line 247, in cleanup
    self._kill_process()
  File "C:\python\lib\site-packages\discord\player.py", line 198, in _kill_process
    proc = self._process
AttributeError: 'FFmpegPCMAudio' object has no attribute '_process'

**Comment by Krutyi-4el** [comment]
> `discord.errors.ClientException: ffmpeg was not found.`

Do you have ffmpeg installed?

**Comment by lokey0905** [comment]
Requirement already satisfied: ffmpeg in c:\python\lib\site-packages (1.4)

**Comment by lokey0905** [comment]
OK I fix it. Need ffmpeg.exe. Lose this file.

**Comment by Krutyi-4el** [comment]
> Requirement already satisfied: ffmpeg in c:\python\lib\site-packages (1.4)

The bot doesn't need `ffmpeg` PyPi package, it needs only `ffmpeg` executable, seems you've already figured it out 👍
