### ISSUE TITLE
Error on installing requirements

### ISSUE THREAD

**Issue by Payzman** [Krutyi-4el/DandelionMusic#35]
I'm getting the following output w/ error message when running `pip -r install requirements.txt`

```
Collecting py-cord[voice]
  Using cached https://github.com/Krutyi-4el/pycord/archive/9c5af3d15e3011ff1e29b55e3b1063391d0455d6.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Processing ./config
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpkndosm0d_in_process.py get_requires_for_build_wheel /tmp/tmpojyl_ksp
       cwd: /tmp/pip-req-build-hsxj3org
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/tmp/tmpkndosm0d_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpkndosm0d_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpkndosm0d_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-uf3fq3sp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-uf3fq3sp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-uf3fq3sp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-uf3fq3sp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 16, in <module>
  ModuleNotFoundError: No module named 'config.config'
  ----------------------------------------
WARNING: Discarding file:///root/Dandelion-Bot/DandelionMusic/config. Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpkndosm0d_in_process.py get_requires_for_build_wheel /tmp/tmpojyl_ksp Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpkndosm0d_in_process.py get_requires_for_build_wheel /tmp/tmpojyl_ksp Check the logs for full command output.
```

I already tried installing the `config` module, but that seems to already exist:

`Requirement already satisfied: config in /usr/local/lib/python3.9/dist-packages (0.5.1)`

any ideas what I might be missing?

**Comment by Payzman** [comment]
> Updating from Python 3.9.x to 3.10.10 seems to have fixed that error I'll see if everything works now :)

**Comment by Payzman** [comment]
Update 2 I am stupid I don't need a "config" module.

However, I had to add the install path of the bot to the PYTHONPATH on debian

**Comment by Krutyi-4el** [comment]
> However, I had to add the install path of the bot to the PYTHONPATH

I thought it's added by default 🤔

**Comment by Payzman** [comment]
Maybe I did change the pythonpath after running pip install -r requirements.txt - I don't remember 100%
