### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#42]
Hi,
if i try to use the newest docker container it throws:

```
Traceback (most recent call last):
  File "/app/run.py", line 92, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 32, in <module>
    bot = MusicBot(
  File "/app/musicbot/bot.py", line 26, in __init__
    self.db_engine = create_async_engine(config.DATABASE)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 85, in create_async_engine
    sync_engine = _create_engine(url, **kw)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 547, in create_engine
    u = _url.make_url(url)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 838, in make_url
    return _parse_url(name_or_url)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 898, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string ''
Press Enter to exit... 
```

i only used the variables:
      - BOT_TOKEN=
      - BOT_PREFIX=-
      - SPOTIFY_SECRET=
      - SPOTIFY_ID=
   
it seems to me like the image is broken...
thx for your help.

**Comment by Krutyi-4el** [comment]
Hello again. Why open second issue on the same topic though?

Regarding the issue
> i only used the variables...

What did you do with other variables? If you've just left `DATABASE_URL` empty (and didn't fully remove it), the sript will get the empty string. As I've said under previous issue, try either removing it completely OR setting it to dummy value if you don't need it (for example, `sqlite:///settings.db`, as in defaults).

**Comment by DerP4si** [comment]
oof sry... i thought it defaults to sqlite:///settings.db always if nothing is given...

**Comment by DerP4si** [comment]
Thx again for your help!... Sry i just forgott my old issue...
