### ISSUE TITLE
module 'asyncio' has no attribute 'Runner'

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#48]
Hi,
If i start the docker with:

```
version: '3'
services:
  bot:
    container_name: Plattenspieler
    image: krutyi4el/dandelion-music:master
    restart: always
    volumes:
      - /mnt/docker/plattenspieler/cookies:/app/config/cookies
    environment:
      - BOT_TOKEN=SOME_TOKEN
      - BOT_PREFIX=-
      - SPOTIFY_SECRET=SOME_TOKEN
      - SPOTIFY_ID=SOME_TOKEN
      - DATABASE_URL=sqlite:///settings.db
```
The following Error get's thrown and it ends in a restartloop:

```
   input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 10, in <module>
    from musicbot import linkutils, utils, loader
  File "/app/musicbot/loader.py", line 13, in <module>
    _runner = asyncio.Runner()
AttributeError: module 'asyncio' has no attribute 'Runner'. Did you mean: 'runners'?
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 10, in <module>
    from musicbot import linkutils, utils, loader
  File "/app/musicbot/loader.py", line 13, in <module>
    _runner = asyncio.Runner()
AttributeError: module 'asyncio' has no attribute 'Runner'. Did you mean: 'runners'?
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 10, in <module>
    from musicbot import linkutils, utils, loader
  File "/app/musicbot/loader.py", line 13, in <module>
    _runner = asyncio.Runner()
AttributeError: module 'asyncio' has no attribute 'Runner'. Did you mean: 'runners'?
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 10, in <module>
    from musicbot import linkutils, utils, loader
  File "/app/musicbot/loader.py", line 13, in <module>
    _runner = asyncio.Runner()
AttributeError: module 'asyncio' has no attribute 'Runner'. Did you mean: 'runners'?
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
```

**Comment by Krutyi-4el** [comment]
Huh, `asyncio.Runner` was added in 3.11... I should've been more careful with what I add to the code.

**Comment by DerP4si** [comment]
So i did nothing wrong for once? 😂

**Comment by DerP4si** [comment]
```      
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 11, in <module>
    from musicbot.playlist import Playlist, LoopMode, LoopState, PauseState
  File "/app/musicbot/playlist.py", line 2, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 11, in <module>
    from musicbot.playlist import Playlist, LoopMode, LoopState, PauseState
  File "/app/musicbot/playlist.py", line 2, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 11, in <module>
    from musicbot.playlist import Playlist, LoopMode, LoopState, PauseState
  File "/app/musicbot/playlist.py", line 2, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
Can't grab subprocess id, something is wrong!
The output is:
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/musicbot/__main__.py", line 11, in <module>
    from musicbot.bot import MusicBot
  File "/app/musicbot/bot.py", line 13, in <module>
    from musicbot.audiocontroller import AudioController
  File "/app/musicbot/audiocontroller.py", line 11, in <module>
    from musicbot.playlist import Playlist, LoopMode, LoopState, PauseState
  File "/app/musicbot/playlist.py", line 2, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
Press Enter to exit... Traceback (most recent call last):
  File "/app/run.py", line 104, in <module>
    input("Press Enter to exit... ")
EOFError: EOF when reading a line
You can close this window and the bot will run in the background
To stop the bot, press Ctrl+C
```

Well 😅

**Comment by Krutyi-4el** [comment]
💀

**Comment by DerP4si** [comment]
its AAALLIIIVEE!!!
haha thx for ur work and fast responses <3
