### ISSUE TITLE
run.py start error

### ISSUE THREAD

**Issue by Aelfriclake** [Krutyi-4el/DandelionMusic#8]
Getting errors while running py.

`Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from musicbot.bot import MusicBot
  File "/home/DandelionMusic/musicbot/bot.py", line 4, in <module>
    from discord.ext import bridge
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/bridge/__init__.py", line 26, in <module>
    from .bot import *
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/bridge/bot.py", line 32, in <module>
    from .context import BridgeApplicationContext, BridgeExtContext
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/bridge/context.py", line 28, in <module>
    from discord.commands import ApplicationContext
  File "/usr/local/lib/python3.8/dist-packages/discord/commands/__init__.py", line 26, in <module>
    from .context import *
  File "/usr/local/lib/python3.8/dist-packages/discord/commands/context.py", line 69, in <module>
    class ApplicationContext(discord.abc.Messageable):
  File "/usr/local/lib/python3.8/dist-packages/discord/commands/context.py", line 337, in ApplicationContext
    @discord.utils.copy_doc(Interaction.edit_original_message)
AttributeError: type object 'Interaction' has no attribute 'edit_original_message'
`

**Comment by Krutyi-4el** [comment]
Could you run `pip freeze` and copy the output here, please?

**Comment by Krutyi-4el** [comment]
No response from the author of the issue; closing.
